# Import Modules

In [1]:
import pandas as pd 
import numpy as np
import os

# Define File path

In [10]:
BASE_DIR = os.path.dirname(os.getcwd())
DATA_PATH = os.path.join(BASE_DIR,"data","raw","train.csv")

print(f"Dataset is at:\n{DATA_PATH}")

Dataset is at:
C:\Projects\AI project\house-price-prediction\data\raw\train.csv

# Load the Dataset

In [17]:
df = pd.read_csv(DATA_PATH)
df = df.iloc[:,1:]

print("Dataset loaded successfully")
print(f"Rows : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Dataset loaded successfully
Rows : 2344
Columns : 82

# Columns Names and Data types

In [33]:
print("="*50)
print("Columns Names and Data types")
print("="*50)
print(df.dtypes.to_string())

==================================================
Columns Names and Data types
==================================================
Order                int64
PID                  int64
MS SubClass          int64
MS Zoning           object
Lot Frontage       float64
Lot Area             int64
Street              object
Alley               object
Lot Shape           object
Land Contour        object
Utilities           object
Lot Config          object
Land Slope          object
Neighborhood        object
Condition 1         object
Condition 2         object
Bldg Type           object
House Style         object
Overall Qual         int64
Overall Cond         int64
Year Built           int64
Year Remod/Add       int64
Roof Style          object
Roof Matl           object
Exterior 1st        object
Exterior 2nd        object
Mas Vnr Type        object
Mas Vnr Area       float64
Exter Qual          object
Exter Cond          object
Foundation          object
Bsmt Qual           object
Bsmt Cond           object
Bsmt Exposure       object
BsmtFin Type 1      object
BsmtFin SF 1       float64
BsmtFin Type 2      object
BsmtFin SF 2       float64
Bsmt Unf SF        float64
Total Bsmt SF      float64
Heating             object
Heating QC          object
Central Air         object
Electrical          object
1st Flr SF           int64
2nd Flr SF           int64
Low Qual Fin SF      int64
Gr Liv Area          int64
Bsmt Full Bath     float64
Bsmt Half Bath     float64
Full Bath            int64
Half Bath            int64
Bedroom AbvGr        int64
Kitchen AbvGr        int64
Kitchen Qual        object
TotRms AbvGrd        int64
Functional          object
Fireplaces           int64
Fireplace Qu        object
Garage Type         object
Garage Yr Blt      float64
Garage Finish       object
Garage Cars        float64
Garage Area        float64
Garage Qual         object
Garage Cond         object
Paved Drive         object
Wood Deck SF         int64
Open Porch SF        int64
Enclosed Porch       int64
3Ssn Porch           int64
Screen Porch         int64
Pool Area            int64
Pool QC             object
Fence               object
Misc Feature        object
Misc Val             int64
Mo Sold              int64
Yr Sold              int64
Sale Type           object
Sale Condition      object
SalePrice            int64

# Sample rows

In [39]:
print("="*50)
print("RANDOM ROWS OF DATASET")
print("="*50)
df.sample(5)

==================================================
RANDOM ROWS OF DATASET
==================================================

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
737,1282,535476370,60,RL,80.0,9760,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,167900
1293,567,533210010,160,FV,40.0,3951,Pave,Pave,Reg,Lvl,...,0,NaN,NaN,NaN,0,6,2009,New,Partial,164500
544,909,909178160,50,RL,60.0,9900,Pave,NaN,Reg,Lvl,...,0,NaN,GdWo,NaN,0,7,2009,WD,Normal,139500
2101,2521,533253090,120,RL,40.0,3874,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,190000
504,2656,902207080,20,RM,49.0,5820,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,126175

# Statistical Summary

In [43]:
print("="*50)
print("Statistical Summary of the dataset")
print("="*50)
df.describe()

==================================================
Statistical Summary of the dataset
==================================================

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2344.000000,2.344000e+03,2344.000000,1951.000000,2344.000000,2344.00000,2344.000000,2344.000000,2344.000000,2325.000000,...,2344.000000,2344.000000,2344.000000,2344.000000,2344.000000,2344.000000,2344.000000,2344.000000,2344.000000,2344.000000
mean,1464.298635,7.143632e+08,57.308020,69.207586,10127.857509,6.06442,5.581911,1970.506826,1983.923635,98.539785,...,94.113055,47.341724,24.731655,2.422782,16.010239,2.582765,58.055034,6.184727,2007.794795,178582.207765
std,842.982263,1.886907e+08,42.802555,23.418018,8050.908132,1.38852,1.105659,30.341434,20.786287,172.239113,...,124.851870,68.037465,67.030943,24.524362,55.820882,38.324145,623.375121,2.708408,1.315117,77125.072713
min,1.000000,5.263011e+08,20.000000,21.000000,1300.000000,1.00000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,737.750000,5.284821e+08,20.000000,58.000000,7466.500000,5.00000,5.000000,1953.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129000.000000
50%,1466.000000,5.354541e+08,50.000000,68.000000,9356.500000,6.00000,5.000000,1972.000000,1992.000000,0.000000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2195.250000,9.071921e+08,70.000000,80.000000,11484.250000,7.00000,6.000000,2000.000000,2003.000000,160.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,210000.000000
max,2930.000000,9.241520e+08,190.000000,313.000000,215245.000000,10.00000,9.000000,2010.000000,2010.000000,1290.000000,...,870.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

# Check for missing values

In [50]:
missing = df.isnull().sum()
missing_percent = (missing*100)/df.shape[0]
missing_report = pd.DataFrame({
    'Missing Count':missing,
    'Missing %' : missing_percent.round(2)
})
missing_report = missing_report[missing_report['Missing Count']>0]
missing_report = missing_report.sort_values('Missing %',ascending=False)

print('='*50)
print(f"Columns with missing values : {len(missing_report)} out of {df.shape[1]}")
print('='*50)
print(missing_report.to_string())

==================================================
Columns with missing values : 26 out of 82
==================================================
                Missing Count  Missing %
Pool QC                  2332      99.49
Misc Feature             2250      95.99
Alley                    2182      93.09
Fence                    1874      79.95
Mas Vnr Type             1426      60.84
Fireplace Qu             1144      48.81
Lot Frontage              393      16.77
Garage Cond               122       5.20
Garage Yr Blt             122       5.20
Garage Finish             122       5.20
Garage Qual               122       5.20
Garage Type               120       5.12
Bsmt Exposure              63       2.69
BsmtFin Type 2             62       2.65
Bsmt Qual                  61       2.60
BsmtFin Type 1             61       2.60
Bsmt Cond                  61       2.60
Mas Vnr Area               19       0.81
BsmtFin SF 1                1       0.04
Bsmt Half Bath              1       0.04
Total Bsmt SF               1       0.04
Bsmt Full Bath              1       0.04
BsmtFin SF 2                1       0.04
Bsmt Unf SF                 1       0.04
Garage Area                 1       0.04
Garage Cars                 1       0.04

# Check for Duplicate Rows

In [53]:
duplicates = df.duplicated().sum()
print(f"Duplicates rows found: {duplicates}")

if(duplicates==0):
    print("No duplicates , Dataset is clean")
else:
    print(f"Found {duplicates} duplicates , need to remove in preprocessing")

Duplicates rows found: 0
No duplicates , Dataset is clean

# Target Variable Analysis

In [56]:
print("TARGET VARIABLE: SalePrice")
print("="*50)
print(f"Min Price : {df['SalePrice'].min()}")
print(f"Max Price : {df['SalePrice'].max()}")
print(f"Mean Price : {df['SalePrice'].mean():,.0f}")
print(f"Median Price : {df['SalePrice'].median():,.0f}")
print(f"Standard Deviation : {df['SalePrice'].std():,.0f}")

TARGET VARIABLE: SalePrice
==================================================
Min Price : 12789
Max Price : 755000
Mean Price : 178,582
Median Price : 160,000
Standard Deviation : 77,125

# Seperate Features and Target

In [64]:
X  = df.drop(columns=['Order','PID','SalePrice'])
Y = df['SalePrice']
print(f"Features Matrix: {X.shape}")
print(f"Target variable shape: {Y.shape}")
print(f"Number of numerical features : {X.select_dtypes(include='number').shape[1]}")
print(f"Number of categorical features : {X.select_dtypes(include='object').shape[1]}")

Features Matrix: (2344, 79)
Target variable shape: (2344,)
Number of numerical features : 36
Number of categorical features : 43